version: 2.1

jobs:
  build:
    macos:
      xcode: 13.4.1

    steps:
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - checkout
            - run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
