version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: "ps1312"
  GHA_Action:
    type: string
    default: "continuous-integration"
  GHA_Event:
    type: string
    default: "pull_request"
  GHA_Meta:
    type: string
    default: ""

jobs:
  macos-job:
    macos:
      xcode: 14.0

    steps:
      - checkout
      - run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

  ios-job:
    macos:
      xcode: 14.0

    steps:
      - checkout
      - run: xcodebuild clean build test -workspace EssentialFeed.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14" ONLY_ACTIVE_ARCH=YES

workflows:
  continuous-integration:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - macos-job
      - ios-job
