name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: continuous-integration
        id: continuous-integration
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
