name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: continuous-integration
        id: continuous-integration
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $CCI_TOKEN
